<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>INICIO</title>
    <link rel="stylesheet" href="css/index.css">
    <style>
        body{
            background: #8f9191;
        }
                
        h1{
             background-color: brown;
            font-family: cursive;
         }
    </style>
</head>
 
<body background=""> 
    
    <nav class="nav">
                <ul class="list"> 
                    <a href="index.html"><img src="img/inicio.png" align="left" width="40" height="40"></a>  
                    <li class="list_item">
                        
                        <a href="INICIO.html">
                        <div class="list_item list_item--click">
                        <img src="logos/inicio.svg"  class="list_img">
                        <a href="INICIO.html" class="nav_link nav_link--inside">INICIO</a>
                        </div>

                        
                    </li>
                    <li class="list_item">
                        <div class="list_button ">
                            <img src="logos/camisa.svg"  class="list_img">
                             <a href="#"  class="nav_link">TIENDA</a>
                            <img src="logos/flechaderecha.svg"  class="list_arrow">
                        </div>
                        <ul class="list_show">
                            <li class="list_inside">
                                <a href="ropahombre.html" class="nav_link nav_link--inside">Caballeros</a>
                            </li>
                            <li class="list_inside">
                                <a href="ropadama.html" class="nav_link nav_link--inside">Damas</a>
                            </li>
                            <li class="list_inside">    
                                <a href="ropaniños.html" class="nav_link nav_link--inside">Niñ@s</a>
                            </li>
                    
                            <li class="list_inside">
                                <a href="ropabebes.html" class="nav_link nav_link--inside">Bebes</a>
                            </li>
                        </ul>
                        <li class="list_item">
                            <div class="list_button">
                            <img src="logos/carrito.svg"  class="list_img">
                            <a href="#"  class="nav_link">CARRITO</a>
                            <img src="logos/flechaderecha.svg"  class="list_arrow">
                            </div>
                            
                            <ul class="list_show">
                                <li class="list_inside">
                                    <a href="vercarrito.html" class="nav_link nav_link--inside">Ver carrito</a>
                                </li>
                                <li class="list_inside">
                                    <a href="pago.html" class="nav_link nav_link--inside">Formas de pago</a>
                                </li>

                            </ul>
                        


                        </li>
                        <li class="list_item">
                            <div class="list_item list_item--click">
                            <img src="logos/telefono.svg"  class="list_img">
                            <a href="contactanos.html" class="nav_link nav_link--inside">CONTACTANOS</a>
                            </div>
                        </li>

                        <li class="list_item">
                            <div class="list_button list_button--click">
                            <img src="logos/usuario.svg"  class="list_img">
                            <a href="#"  class="nav_link">USUARIO</a>
                            </div>
                            
                            <ul class="list_show">
                                <li class="list_inside">
                                    <p>Carlos Cano</p>
                                    <p>Julian Morales</p>
                                    <p>Jonathan Pinilla</p>
                                </li>
                            </ul>
                        </li>                     
                   </li>  
                </ul>
    </nav>
    <span class="linea"></span>
    <center> <h1>GALERIA DE IMAGENES</h1></center>
        <span class="linea"></span>
        <section class="galeria">
            <a href="#image1"><img src="img/imagen1.jpg" alt=""></a>
            <a href="#image2"><img src="img/imagen2.jpg" alt=""></a>
            <a href="#image3"><img src="img/imagen3.jpg" alt=""></a>
            <a href="#image4"><img src="img/imagen4.jpg" alt=""></a>
            <a href="#image5"><img src="img/imagen5.jpg" alt=""></a>
            <a href="#image6"><img src="img/imagen6.jpg" alt=""></a>
            <a href="#image6"><img src="img/imagen.jpg" alt=""></a>
        </section>

        <article class="light-box" id="image1">
            <a href="#image6"  class="next"><i class="fas fa-arrow-left"></i></a>    
            <img src="img/imagen1.jpg" alt="">
            <a href="#image2"  class="next"><i class="fas fa-arrow-right"></i></a>
            <a href="#"  class="close">X</a>
        </article>

        <article class="light-box" id="image2">
            <a href="#image1"  class="next"><i class="fas fa-arrow-left"></i></a>
            <img src="img/imagen2.jpg" alt="">
            <a href="#image3"  class="next"><i class="fas fa-arrow-right"></i></a>
            <a href="#"  class="close">X</a>
        </article>

        <article class="light-box" id="image3">
            <a href="#image2"  class="next"><i class="fas fa-arrow-left"></i></a>
            <img src="img/imagen3.jpg" alt="">
            <a href="#image4"  class="next"><i class="fas fa-arrow-right"></i></a>
            <a href="#"  class="close">X</a>
        </article>

        <article class="light-box" id="image4">
            <a href="#image3"  class="next"><i class="fas fa-arrow-left"></i></a>
            <img src="img/imagen4.jpg" alt="">
            <a href="#image5"  class="next"><i class="fas fa-arrow-right"></i></a>
            <a href="#"  class="close">X</a>
        </article>

        <article class="light-box" id="image5">
            <a href="#image4"  class="next"><i class="fas fa-arrow-left"></i></a>
            <img src="img/imagen5.jpg" alt="">
            <a href="#image6"  class="next"><i class="fas fa-arrow-right"></i></a>
            <a href="#"  class="close">X</a>
        </article>

        <article class="light-box" id="image6">
            <a href="#image5"  class="next"><i class="fas fa-arrow-left"></i></a>
            <img src="img/imagen6.jpg" alt="">
            <a href="#image1"  class="next"><i class="fas fa-arrow-right"></i></a>
            <a href="#"  class="close">X</a>
        </article>

    
    <script src="https://kit.fontawesome.com/c15b744a04.js" crossorigin="anonymous"></script>
</body>

</html>
